[project]
name = "repo-tokens-calculator"
version = "0.1.0"
description = "CLI token counter for files and directories using tiktoken (uv-managed)"
requires-python = ">=3.12"
dependencies = [
    "tiktoken>=0.11.0",
]
